name: mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# with an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0
  http_parser: ^4.0.0
  image_picker: ^0.8.7+7
  image: ^4.0.17
  flutter_secure_storage: ^10.3.1
  cookie_jar: ^4.0.9
  dio_cookie_manager: ^3.4.0
  intl: ^0.20.0
  url_launcher: ^6.3.1
  path_provider: ^2.0.0
  flutter_dotenv: ^5.1.0
  js: ^0.6.7
  flutter_screenutil: ^5.9.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0
  geolocator: ^14.0.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
